---
- hosts: localhost
  vars: 
   password: redhat
  tasks: 
  - user: 
     name: "{{ item }}"
     update_password: on_create
     state: present
     password: "{{ password  | password_hash('sha512') }}"
    loop:
    - mayank
    - test

